CC=g++
CFLAGS=-I.


				// make string1
string1.o: string1.cpp
	${CC} -c string1.cpp
string1: string1.o
	${CC} ${CFLAGS} string1.o -o string1


				// make floatingpoint
floatingpoint.o: floatingpoint.c
	${CC} -c floatingpoint.c
floatingpoint: floatingpoint.o
	${CC} ${CFLAGS} floatingpoint.o -o floatingpoint


				//
