CC=g++
#CFLAGS=-I.
X=part1
Y=readnames


		#make part1
${X}.o : ${X}.cpp
	${CC} -c ${X}.cpp ;
${X}: ${X}.o
	${CC} ${X}.o -o ${X};



		#make readnames
${y}.o : ${y}.cpp
	${CC} -c ${y}.cpp ;
${y}: ${y}.o
	${CC} ${y}.o -o ${y};
